FROM node:slim
WORKDIR /usr/src/app

# We don't need the standalone Chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV AMAZON_USERNAME = ${AMAZON_USERNAME}
ENV AMAZON_PASSWORD = ${AMAZON_PASSWORD}
ENV AMAZON_TLD = ${AMAZON_TLD}
ENV AMAZON_YEAR_FILTER = ${AMAZON_YEAR_FILTER}
ENV AMAZON_PAGE_FILTER = ${AMAZON_PAGE_FILTER}
ENV AMAZON_ONLY_NEW = ${AMAZON_ONLY_NEW}
ENV FILE_DESTINATION_FOLDER = "./data/"
ENV FILE_FALLBACK_EXTENSION = ".pdf"
ENV DEBUG = ${AMAZON_PASSWORD}
ENV LOG_PATH = ${LOG_PATH}
ENV LOG_LEVEL = ${LOG_LEVEL}
ENV RECURRING = true
ENV RECURRING_PATTERN = ${RECURRING_PATTERN}

RUN npm install -g concurrently
CMD ["concurrently","npx docudigger scrape all"]