name: Semantic release
on: 
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
    branches:
      - 'main'
      - 'dev'
env:
  GH_TOKEN: ${{ secrets.AUTH_GH }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm ci
      - run: npm run semantic-release:ci
